title: Відеопрозорість Бровари
baseurl: "" # Set this to "/repository-name" if hosted on a subpath
markdown: kramdown
permalink: pretty

# Define collections
collections:
  posts:
    output: true
    permalink: /:name/ # Ensure posts are available from the root
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: "posts"
    values:
      layout: default
  - scope:
      path: "pages"
    values:
      layout: default
