title: Відеопрозорість Бровари
baseurl: "" # leave this empty for GitHub Pages
markdown: kramdown
permalink: pretty

# Define collections
collections:
  posts:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: "posts"
    values:
      layout: default