title: Відеопрозорість Бровари
description: Бровари. Політичні та суспільні відеоновини
baseurl: "/video.brovary.org" # the subpath of your site, e.g. /blog
url: "https://sergilliukhin.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
permalink: /:name/

# Collections
collections:
  pages:
    output: true
    permalink: /:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      coverImage: "{{ page.coverImage | prepend: '/assets/images/' }}"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      coverImage: "{{ page.coverImage | prepend: '/assets/images/' }}"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 