title: Відеопрозорість Бровари
baseurl: "" # Set this to "/repository-name" if hosted on a subpath
markdown: kramdown
permalink: /:name

# Define collections
collections:
  posts:
    output: true
    permalink: /:name 
  pages:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: "posts"
    values:
      layout: default
  - scope:
      path: "pages"
    values:
      layout: default
