title: Відеопрозорість Бровари
description: Бровари. Політичні та суспільні відеоновини
baseurl: "/video.brovary.org" # the subpath of your site, e.g. /blog
url: "https://sergilliukhin.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
permalink: /:title/

# Collections
collections:
  pages:
    output: true
    permalink: /:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      coverImage: "{{ page.coverImage }}"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      coverImage: "{{ page.coverImage }}"
      permalink: /:title/
  - scope:
      path: "404.md"
    values:
      layout: "home"
      permalink: /404.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - image_path_processor

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

image_path: "{{ site.baseurl }}/assets/images/" 