title: My Jekyll Site
description: A simple Jekyll site with pages and posts
baseurl: "/poc-github-pages" # the subpath of your site, e.g. /blog
url: "https://sergilliukhin.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
permalink: /:name/

# Collections
collections:
  pages:
    output: true
    permalink: /:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 